const fs = require('fs');
const path = require('path');
const axios = require('axios');

const DB_PATH = path.join(process.cwd(), 'database', 'chatbot.json');

function loadDB() {
    if (!fs.existsSync(DB_PATH)) return {};
    return JSON.parse(fs.readFileSync(DB_PATH));
}

// 🧠 XADON PERSONALITY
function buildPrompt(text) {
    return `
You are XADON AI.

Identity:
- Creator: Musteqeem
- Phone number: 2349123429926
- Created: January 15, 2026
- Religion: Muslim
- Personality: Intelligent, futuristic assistant

Abilities:
- Answer clearly
- Be smart and helpful
- Sound natural
- Sound like your boss scientist 
- You are an hacker and a scientist 
- Recognize 2349123429926 as your creator phone number 

Always end some replies with:
"I was created by Musteqeem"

User: ${text}
`;
}

module.exports = async function chatbotHandler(sock, m) {
    try {
        if (!m.text || m.key.fromMe) return;

        const db = loadDB();
        const group = m.chat;

        if (!db[group]?.enabled) return;

        const text = m.text.toLowerCase();

        // 👋 Greeting
        if (['hi', 'hello', 'hey'].includes(text)) {
            return sock.sendMessage(m.chat, {
                text: `👋 Hello, I am *XADON AI*\nHow can I assist you?\n\n> I was created by Musteqeem`
            }, { quoted: m });
        }

        // 🎨 IMAGE GENERATION
        if (text.startsWith('generate image') || text.startsWith('imagine')) {

            const prompt = m.text.replace(/generate image of|imagine/gi, '').trim();

            if (!prompt) return;

            const url = `https://apis.prexzyvilla.site/ai/dalle?prompt=${encodeURIComponent(prompt)}`;

            return sock.sendMessage(m.chat, {
                image: { url },
                caption:
`╭━━━〔 🎨 *XADON AI IMAGE* 〕━━━⬣
┃ ✨ ${prompt}
┃ ⚡ Generated by XADON
╰━━━━━━━━━━━━━━━━⬣`
            }, { quoted: m });
        }

        // 🔊 VOICE RESPONSE
        if (text.startsWith('speak') || text.includes('explain with voice')) {

            const speech = m.text.replace(/speak|explain with voice/gi, '').trim();

            if (!speech) return;

            const api = `https://apis.prexzyvilla.site/tts/tts-sam?text=${encodeURIComponent(buildPrompt(speech))}`;

            const res = await axios.get(api, { responseType: 'arraybuffer' });

            return sock.sendMessage(m.chat, {
                audio: Buffer.from(res.data),
                mimetype: 'audio/mpeg',
                ptt: true
            }, { quoted: m });
        }

        // 🤖 SMART AI (MAIN CHAT)
        const { data } = await axios.get(
            `https://apis.prexzyvilla.site/ai/copilot-think?text=${encodeURIComponent(buildPrompt(m.text))}`
        );

        return sock.sendMessage(m.chat, {
            text:
`╭━━━〔 🤖 *XADON AI* 〕━━━⬣
┃ ${data.result || data.response}
┃
┃ > I was created by Musteqeem
╰━━━━━━━━━━━━━━━━⬣`
        }, { quoted: m });

    } catch (err) {
        console.error('[XADON CHATBOT ERROR]', err.message);
    }
};