const fs = require('fs').promises; // ← use promises version → cleaner async
const path = require('path');

module.exports = {
    command: 'html',
    aliases: ['tohtml', 'text2html', 'webpage', 'htmlify'],
    category: 'documents',
    desc: 'Convert text → styled .html document',

    emoji: {
        wait:     '✨',
        success:  '📄',
        error:    '❌',
        thinking: '⚡'
    },

    cooldown: 7,

    execute: async (sock, m, { args, q, prefix, command, reply }) => {
        const { emoji } = module.exports;

        let filePath = null;

        try {
            // ── Collect text ────────────────────────────────────────
            let text = q?.trim() || '';

            if (!text && m.quoted) {
                text = (
                    m.quoted.text ||
                    m.quoted.caption ||
                    m.quoted.description ||
                    ''
                ).trim();
            }

            if (!text) {
                return reply(
                    `${emoji.error} No text provided.\n` +
                    `Reply to a message or use:\n${prefix + command} Your text here`
                );
            }

            if (text.length > 18000) {
                text = text.slice(0, 17980) + '… (truncated)';
            }

            await reply(
                `${emoji.wait} Generating HTML document…\n` +
                `  Length → ${text.length.toLocaleString()} chars`
            );

            await sock.sendMessage(m.chat, {
                react: { text: emoji.thinking, key: m.key }
            });

            // ── HTML content ────────────────────────────────────────
            const safeText = text
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/\n/g, '<br>');

            const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XADON Document</title>
  <style>
    body {font-family:system-ui,sans-serif; background:#0f0f17; color:#e0e0ff; margin:0; padding:2rem; line-height:1.6;}
    .container {max-width:860px; margin:0 auto; background:#1a1a2e; padding:2.5rem; border-radius:16px; box-shadow:0 10px 40px #0006;}
    h1 {color:#7b5eff; text-align:center; margin-bottom:2rem;}
    .content {white-space:pre-wrap; font-size:1.05rem;}
    .footer {margin-top:3rem; text-align:center; font-size:0.9rem; color:#888; border-top:1px solid #333; padding-top:1.5rem;}
  </style>
</head>
<body>
  <div class="container">
    <h1>XADON Document</h1>
    <div class="content">${safeText}</div>
    <div class="footer">Generated by XADON • ${new Date().toLocaleString('en-NG')}</div>
  </div>
</body>
</html>`;

            // ── Temp folder – safe relative path ────────────────────
            const tempDir = path.join(process.cwd(), 'temp'); // ← most reliable fix

            try {
                await fs.mkdir(tempDir, { recursive: true });
            } catch (mkdirErr) {
                console.error('[TEMP MKDIR]', mkdirErr);
                throw new Error('Cannot create temp folder – check bot hosting permissions');
            }

            const fileName = `XADON_${Date.now().toString(36).toUpperCase()}.html`;
            filePath = path.join(tempDir, fileName);

            await fs.writeFile(filePath, html, 'utf8');
            const buffer = await fs.readFile(filePath);

            // ── Send ────────────────────────────────────────────────
            await sock.sendMessage(m.chat, {
                document: buffer,
                mimetype: 'text/html',
                fileName,
                caption:
                    `📄 ${fileName}\n` +
                    `├ Characters → ${text.length.toLocaleString()}\n` +
                    `├ Opens as webpage\n` +
                    `└ XADON • ${new Date().toLocaleDateString('en-NG')}`
            }, { quoted: m });

            await reply(
                `${emoji.success} HTML file created!\n` +
                `→ *${fileName}*\n` +
                `Tap to download • opens in browser`
            );

            await sock.sendMessage(m.chat, {
                react: { text: emoji.success, key: m.key }
            });

        } catch (err) {
            console.error('[HTML CMD]', err);

            await reply(
                `${emoji.error} Failed to create HTML\n` +
                `→ ${err.message?.slice(0, 100) || 'Unknown error'}`
            );

            await sock.sendMessage(m.chat, {
                react: { text: emoji.error, key: m.key }
            });

        } finally {
            // Cleanup even on error
            if (filePath) {
                setTimeout(async () => {
                    try { await fs.unlink(filePath); } catch {}
                }, 10000);
            }
        }
    }
};