//© By Musteqeem 2026 please do not edit this file use as it is 
module.exports = {
  command: 'info',
  alias: ['about', 'botinfo'],
  description: '*Musteqeem MD* :Show bot and owner details',
  category: 'owner',

  execute: async (sock, m, { reply }) => {
    try {
      const owner = 'https://wa.me/234902342XADON'; 
      const repo = 'https://github.com/CEOcybershieldquad/XADON-AI'; 
      const web = 'https://xadon.ai/xxxx-xxxx'; 
      const creator = 'MUSTEQEEM'; 
      const channel = 'https://whatsapp.com/channel/0029Vb7ACifD38Cb7Jlj5w3B'
      const group = 'https://chat.whatsapp.com/Besbj8VIle1GwxKKZxadonx?mode=gi_t'
      const infoText = `
╭───〔 ☬ 𝐗𝐀𝐃𝐎𝐍 BOT INFO ☬ 〕───╮
│
│ 👑 Creator: ${creator}
│ 🤖 Owner WhatsApp: ${owner}
│ 📦 Repository: ${repo}
│ 🌀 Website: ${web}│  
| 👾 WhatsApp group ${group}
|🔊 channel: ${channel}
╰───────────────────────────────╯
`;

      await reply(infoText);
    } catch (err) {
      console.error('Info plugin error:', err);
      await reply('Failed to fetch info. Try again.');
    }
  }
};
